sonar.projectKey=pokemon-api
sonar.projectName=pokemon-api
sonar.projectVersion=1.0

# Ruta del proyecto
sonar.sources=src

# Encoding
sonar.sourceEncoding=UTF-8

# Para TypeScript
sonar.javascript.node.maxspace=4096

# Reportes opcionales (si usas Jest)
sonar.tests=src
sonar.test.inclusions=**/*.test.ts, **/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
